<a href="https://colab.research.google.com/github/saba-0h/Python-for-ML-090/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,6,8,10]
a=np.array(arr1)
b=np.array(arr2)
print(a,b)#original
print(a+b)#add
print(a-b)#subract
print(a*b)#multiply
print(a/b)#divide
print(a.dot(b))#dot product
sclr=5
print("Result", a*sclr)#scalar multiply
def my_func(x,y):
  if x>y:
    return x-y
  else:
    return x+y
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("result", vec_func(arr1,arr2))

[10 20 30 40 50] [ 2  4  6  8 10]
[12 24 36 48 60]
[ 8 16 24 32 40]
[ 20  80 180 320 500]
[5. 5. 5. 5. 5.]
1100
Result [ 50 100 150 200 250]
result [ 8  1 50]
