<a href="https://colab.research.google.com/github/saba-0h/Python-for-ML-090/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[1,2,4],[5,8,9],[2,4,2]])
print("Array created\n",a)
#creating array in numpy wowow


Array created
 [[1 2 4]
 [5 8 9]
 [2 4 2]]


In [ ]:
b = np.zeros((3,4))
print("Array is\n", b)

Array is
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#constant value
c=np.full((3,3),6)
print("All in 6's\n", c)

All in 6's
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#random array values
d=np.random.random((2,2))
print(d)

[[0.22486044 0.55118099]
 [0.89507321 0.28252241]]


In [ ]:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]
[ 0  5 10 15 20 25] [ 0  5 10 15 20 25]


In [ ]:
f=np.array([[1,2,3,4],[6,5,3,2],[5,8,1,2],[10,4,2,1],[5,6,7,4]])
newf=f.reshape(4,5)
print("Newly arranged one\n",newf)

Newly arranged one
 [[ 1  2  3  4  6]
 [ 5  3  2  5  8]
 [ 1  2 10  4  2]
 [ 1  5  6  7  4]]


In [ ]:
flarr=a.flatten()
print("Ori\n", a)
print("\n", flarr)

Ori
 [[1 2 4]
 [5 8 9]
 [2 4 2]]

 [1 2 4 5 8 9 2 4 2]


In [ ]:
arr=np.array([[1,2,3,4],[3,2,4,2],[3,2,1,2]])
print("\nNo. of dimesnions is", arr.ndim)
print("Shape of array",arr.shape)
print("\nNo. of array", arr.size)
print("\nArray type", arr.dtype)
newtype=arr.astype('f')
print("\nConverted array", newtype)
print("\nConverted type", newtype.dtype)


No. of dimesnions is 2
Shape of array (3, 4)

No. of array 12

Array type int64

Converted array [[1. 2. 3. 4.]
 [3. 2. 4. 2.]
 [3. 2. 1. 2.]]

Converted type float32


In [ ]:
p=np.array([[1,4,2,6],[6,9,5,2],[9,5,3,2],[8,4,3,2]])
print(p[3:0:-1])
print("\n",p[1:3:1])
print("\n",p[3:,3])

[[8 4 3 2]
 [9 5 3 2]
 [6 9 5 2]]

 [[6 9 5 2]
 [9 5 3 2]]

 [2]
