<a href="https://colab.research.google.com/github/saba-0h/Python-for-ML-090/blob/main/numpy2_090.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1,2,0,4],[4,-0.5,6,0],[2,6,7,8],[3,-7,4,2]])
print("Original array:\n", arr)

Original array:
 [[ 1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.   6.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
print("Every other rows:\n", arr[::2])


Every other rows:
 [[1. 2. 0. 4.]
 [2. 6. 7. 8.]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print("Original array:", arr)
print("Return every other element in the array :", arr[::2])


Original array: [1 2 3 4 5 6 7]
Return every other element in the array : [1 3 5 7]


In [ ]:
arr = np.array([[1,2,0,4],[4,-0.5,6,0],[2,6,7,8],[3,-7,4,2]])
temp = arr[:2, :3]
print("\nArray with first 2 rows and 3 columns:\n", temp)



Array with first 2 rows and 3 columns:
 [[ 1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [ ]:
newarr = np.array([[0,1,2,3],[3,2,1,0]])
print("\nElements at indices(0,3),(1,2),(2,1),(3,0):\n", newarr)



Elements at indices(0,3),(1,2),(2,1),(3,0):
 [[0 1 2 3]
 [3 2 1 0]]


In [ ]:
cond = arr > 2
temp = arr[cond]
print("\nElements greater than 2:\n", temp)



Elements greater than 2:
 [4. 4. 6. 6. 7. 8. 3. 4.]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [ ]:
arr3 = np.hstack((arr1, arr2))
print(arr3)


[1 2 3 4 5 6]


In [ ]:
arr4 = np.vstack((arr1, arr2))
print(arr4)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr5 = np.dstack((arr1, arr2))
print(arr5)


[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
arr6 = np.array_split(arr, 3)
print(arr)
print(arr6)
print(arr6[0])
print(arr6[1])
print(arr6[2])


[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
