<a href="https://colab.research.google.com/github/saba-0h/Python-for-ML-090/blob/main/Skill_Test_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
# Feature data
X = np.array([
    [1, 50, 1, 2],
    [1.5, 60, 0.5, 3],
    [0.8, 55, 1.2, 1.6],
    [2, 40, 1, 4],
    [1.2, 65, 0.8, 2.4],
    [1.7, 45, 1.5, 3.4],
    [0.9, 70, 1, 1.8],
    [2.1, 35, 1.3, 4.2],
    [1.1, 60, 0.9, 2.2],
    [1.8, 48, 1, 3.6],
    [0.95, 62, 1.1, 1.9],
    [2.2, 42, 0.7, 4.4],
    [1, 58, 1, 2],
    [1.9, 46, 1.2, 3.8],
    [1.3, 66, 0.6, 2.6]
])
# Labels (Sine=0, Square=1)
y = np.array([0,1,0,1,0,1,0,1,0,1,0,1,0,1,0])
# Feature scaling (important for KNN)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# Create KNN model
k = 3
model = KNeighborsClassifier(n_neighbors=k)
# Train model
model.fit(X_scaled, y)
# Example prediction
new_signal = np.array([[1.4, 55, 1, 2.8]])
new_signal_scaled = scaler.transform(new_signal)
prediction = model.predict(new_signal_scaled)
print("Predicted Class:", "Sine" if prediction[0] == 0 else "Square")

Predicted Class: Sine


In [2]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
# Feature dataset: [Voltage, Current]
X = np.array([
    [5, 0.5],
    [5.5, 0.4],
    [4.8, 0.6],
    [6, 0.3],
    [6.5, 0.2],
    [6.2, 0.25],
    [4.9, 0.55],
    [5.8, 0.35],
    [5.2, 0.5],
    [6.3, 0.22]
])
# Labels: Working = 0, Defective = 1
y = np.array([
0, 0, 0, 1, 1,
1, 0, 1, 0, 1
])
# Create KNN model
model = KNeighborsClassifier(n_neighbors=3)
# Train the model
model.fit(X, y)
# Predict on same dataset (since no test data given)
predictions = model.predict(X)
# Print results
print("Predicted Labels:")
print(predictions)
print("Actual Labels:")
print(y)

Predicted Labels:
[0 0 0 1 1 1 0 1 0 1]
Actual Labels:
[0 0 0 1 1 1 0 1 0 1]


In [3]:
 import numpy as np
from sklearn.linear_model import LinearRegression
# Given dataset
# Study Hours (X)
X = np.array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(-1, 1)
# Final Exam Scores (y)
y = np.array([50, 55, 60, 65, 68, 70, 78, 75, 82, 85])
# Create Linear Regression model
model = LinearRegression()
# Train the model
model.fit(X, y)
# Predict scores for the same inputs (since no new data is given)
predictions = model.predict(X)
# Print predictions
print("Predicted Scores:")
print(predictions)
# Print actual scores
print("Actual Scores:")
print(y)
# Example: Predict score for a new student who studies 7.5 hours
new_hours = np.array([[7.5]])
predicted_score = model.predict(new_hours)
print("Predicted score for 7.5 study hours:", predicted_score[0])

Predicted Scores:
[51.89090909 55.64848485 59.40606061 63.16363636 66.92121212 70.67878788
 74.43636364 78.19393939 81.95151515 85.70909091]
Actual Scores:
[50 55 60 65 68 70 78 75 82 85]
Predicted score for 7.5 study hours: 68.8


In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression
# Given dataset
# Year (independent variable)
X = np.array([2010, 2011, 2012, 2013, 2014,
              2015, 2016, 2017, 2018, 2019]).reshape(-1, 1)
# Price in Lakhs (dependent variable)
y = np.array([25, 28, 30, 34, 37, 40, 43, 45, 47, 50])
# Create Linear Regression model
model = LinearRegression()
# Train the model
model.fit(X, y)
# Predict prices for given years
predictions = model.predict(X)
# Print predicted prices
print("Predicted Prices:")
print(predictions)
# Print actual prices
print("Actual Prices:")
print(y)
# Example: Predict price for year 2020
future_year = np.array([[2020]])
predicted_price = model.predict(future_year)
print("Predicted price for 2020 (in Lakhs):", predicted_price[0])

Predicted Prices:
[25.27272727 28.07878788 30.88484848 33.69090909 36.4969697  39.3030303
 42.10909091 44.91515152 47.72121212 50.52727273]
Actual Prices:
[25 28 30 34 37 40 43 45 47 50]
Predicted price for 2020 (in Lakhs): 53.33333333333303


In [5]:
 import numpy as np
from sklearn.cluster import KMeans
# Given dataset: [Voltage, Current]
X = np.array([
    [4.819941, 0.87293],
    [5.249786, 0.918358],
    [4.771151, 0.958775],
    [4.602712, 1.087788],
    [4.814919, 0.877739],
    [12.38281, 2.257141],
    [12.36406, 2.383657],
    [11.22958, 1.89107],
    [12.17975, 1.82507],
    [12.0638, 2.29575]
])
# Apply KMeans with 2 clusters
kmeans = KMeans(n_clusters=2, random_state=0)
# Fit the model
kmeans.fit(X)
# Get cluster labels
labels = kmeans.labels_
# Get cluster centers
centers = kmeans.cluster_centers_
# Print results
print("Cluster Labels:")
print(labels)
print("\nCluster Centers:")
print(centers)

Cluster Labels:
[1 1 1 1 1 0 0 0 0 0]

Cluster Centers:
[[12.044      2.1305376]
 [ 4.8517018  0.943118 ]]


In [6]:
import pandas as pd
import numpy as np
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9], [np.nan, np.nan, np.nan]], columns=['A', 'B', 'C'])
print("Original DataFrame\n",df)
print("Aggregate function: aggregate()\n", df.aggregate(['sum']))
print("Aggregate function: alias agg()\n", df.agg(['sum']))

Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN
Aggregate function: aggregate()
         A     B     C
sum  12.0  15.0  18.0
Aggregate function: alias agg()
         A     B     C
sum  12.0  15.0  18.0


In [7]:
#Aggregate function to produce sum,min and max
a=df.agg(['sum', 'min', 'max'])
print("\nOriginal DataFrame\n",df)
print("\nAggregate function to produce sum, min and max\n",a)


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Aggregate function to produce sum, min and max
         A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0
max   7.0   8.0   9.0


In [8]:
#Different aggregation per column
b=df.agg({'A': ['sum', 'min'], 'B': ['min', 'max']})
print("\nOriginal DataFrame\n",df)
print("\nDifferent aggregations per column\n",b)


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Different aggregations per column
         A    B
sum  12.0  NaN
min   1.0  2.0
max   NaN  8.0


In [9]:
#Aggregate different functions over the columns and rename the index of the resulting DataFrame
c=df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))
print("\nOriginal DataFrame\n",df)
print("\nAggregate different functions over the columns and rename the index of the resulting DataFrame\n",c)


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Aggregate different functions over the columns and rename the index of the resulting DataFrame
      A    B    C
x  7.0  NaN  NaN
y  NaN  2.0  NaN
z  NaN  NaN  6.0


/tmp/ipykernel_3306/2560020860.py:2: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  c=df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))
/tmp/ipykernel_3306/2560020860.py:2: FutureWarning: The provided callable <function mean at 0x79dc15d35940> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  c=df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))


In [10]:
#Aggregate over the rows
d=df.agg("sum", axis="columns")
print("\nOriginal DataFrame\n",df)
print("\nAggregate-Sum: row wise\n",d)


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Aggregate-Sum: row wise
 0     6.0
1    15.0
2    24.0
3     0.0
dtype: float64


In [11]:
#Aggregate over the columns
e=df.agg("sum", axis="rows")
print("\nOriginal DataFrame\n",df)
print("\nAggregate-Sum: Column wise\n", e)


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Aggregate-Sum: Column wise
 A    12.0
B    15.0
C    18.0
dtype: float64


In [12]:
#Summary of aggregate function using describe
print("\nOriginal DataFrame\n",df)

print("\nSummary of aggregate functions using describe()\n",df.describe())


Original DataFrame
      A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

Summary of aggregate functions using describe()
          A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0


# DATA GROUPING

In [13]:
import pandas as pd
df = pd.DataFrame({'Animal' : ['Tiger','Lion','Cheetah','Deer'],
'Max speed' : ['130','110','180','160']})
print(df)

    Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160


In [14]:
b=df.groupby(['Animal']).sum()
print("\nOriginal DataFrame\n",df)
print("\nGroup by through Column using sum\n",b)


Original DataFrame
     Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160

Group by through Column using sum
         Max speed
Animal           
Cheetah       180
Deer          160
Lion          110
Tiger         130


In [15]:
c=df.groupby(['Animal']).count()
print("\nOriginal DataFrame\n",df)
print("\nGroup by through Column using count\n",c)


Original DataFrame
     Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160

Group by through Column using count
          Max speed
Animal            
Cheetah          1
Deer             1
Lion             1
Tiger            1


In [16]:
d=df.groupby(['Animal']).first()
print("\nOriginal DataFrame\n",df)
print("\nGroup by through Column using first\n",d)


Original DataFrame
     Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160

Group by through Column using first
         Max speed
Animal           
Cheetah       180
Deer          160
Lion          110
Tiger         130


In [17]:
e=df.groupby(['Animal']).last()
print("\nOriginal DataFrame\n",df)
print("\nGroup by through Column using last\n",e)


Original DataFrame
     Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160

Group by through Column using last
         Max speed
Animal           
Cheetah       180
Deer          160
Lion          110
Tiger         130


In [18]:
f=df.groupby(['Animal']).size()
print("\nOriginal DataFrame\n",df)
print("\nGroup by through Column using size\n",f)


Original DataFrame
     Animal Max speed
0    Tiger       130
1     Lion       110
2  Cheetah       180
3     Deer       160

Group by through Column using size
 Animal
Cheetah    1
Deer       1
Lion       1
Tiger      1
dtype: int64
